spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    continue-on-error: false
    hikari:
      maximum-pool-size: 2
      pool-name: webflux
      validation-timeout: 5000
    url: jdbc:mysql://localhost:3306/webflux
    username: webflux
    password: webflux
    data: classpath:data-mysql.sql
    platform: mysql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    pool:
      validation-query: select 1
    username: webflux
    password: webflux
server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: ERROR
    org.springframework: DEBUG
    org.springframework.beans.factory.support.DefaultListableBeanFactory: OFF
    com.nhn: DEBUG

