spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    continue-on-error: false
    hikari:
      maximum-pool-size: 2
      pool-name: [webflux]
      validation-timeout: 5000
    url: jdbc:mysql://133.186.217.82:3306/webflux
    username: webflux
    password: webflux
    data: classpath:data-mysql.sql
    platform: mysql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 133.186.217.82
    port: 6379
  http:
    log-request-details: true
  data:
    mongodb:
      username: webflux
      password: webflux
      host: 133.186.217.82
      port: 27017
      database: webflux
  kafka:
    consumer:
      group-id: webflux
      bootstrap-servers: 10.162.5.97:9092,10.162.5.97:9093,10.162.5.97:9094
      auto-commit-interval: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: true
      properties:
        topic: webflux
        spring:
          json:
            trusted:
              packages: com.nhn.mongo

    producer:
      bootstrap-servers: 10.162.5.97:9092,10.162.5.97:9093,10.162.5.97:9094
      acks: all
      retries: 0
      batch-size: 20000
      buffer-memory: 3000000
      properties:
        linger:
          ms: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    root: WARN
    com.nhn: DEBUG
    org.springframework: WARN
    org.springframework.beans.factory.support.DefaultListableBeanFactory: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
    org.springframework.web.reactive.function: TRACE

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.zaxxer.hikari: ERROR

    org.springframework.data: DEBUG
    org.springframework.kafka: DEBUG
    io.lettuce.core.protocol.CommandEncoder: TRACE

    reactor.Mono: INFO
    reactor.Flux: INFO
    reactor.kafka: DEBUG
    web: ERROR


