spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    continue-on-error: false
    hikari:
      maximum-pool-size: 2
      pool-name: [webflux]
      validation-timeout: 5000
    url: jdbc:mysql://localhost:3306/webflux
    username: webflux
    password: webflux
    data: classpath:data-mysql.sql
    platform: mysql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
  http:
    log-request-details: true
  data:
    mongodb:
      username: webflux
      password: webflux
      host: localhost
      port: 27017
      database: webflux

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    root: WARN
    com.nhn: DEBUG
    org.springframework: ERROR
    org.springframework.beans.factory.support.DefaultListableBeanFactory: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
#    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    # log routingFunctionMapping
#    org.springframework.web.reactive.function: TRACE

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.zaxxer.hikari: ERROR

    org.springframework.data: TRACE
    io.lettuce.core.protocol.CommandEncoder: TRACE

    reactor.Mono: DEBUG
    reactor.Flux: DEBUG
    web: ERROR


