spring:
  r2dbc:
    url: r2dbc:pool:mysql://133.186.217.82:3306/webflux
    username: webflux
    password: webflux
    pool:
      validation-query: select 'r2dbc'
      max-size: 3
      initial-size: 3
      max-idle-time: 5m

logging:
  level:
    com.nhn: DEBUG
    org.springframework: INFO
    org.springframework.data.r2dbc.core: DEBUG
    org.springframework.transaction.interceptor: TRACE
#    org.springframework.data.r2dbc.connectionfactory: DEBUG
#    com.github.jasync: DEBUG
#    root: WARN
